// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhwxqrusnoloftaprgqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZod3hxcnVzbm9sb2Z0YXByZ3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0OTI1NTMsImV4cCI6MjA2MDA2ODU1M30.36wS9Jj73BufbhN-7NR-WGz7kBaKqwuZxBp4ztjahE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);